component output = false
{
	this.name = 'flmounts';
	this.datasource = 'forums';
	
	boolean function onRequestStart( string TargetPage ) output = false
	{
		Request.TierJSON = '{"T11":{"REQUIRED":[{"icon":"ability_hunter_pet_worm","id":5306.0},{"icon":"achievement_dungeon_blackwingdescent_darkironcouncil","id":5307.0},{"icon":"inv_misc_bell_01","id":5308.0},{"icon":"warrior_talent_icon_furyintheblood","id":5309.0},{"icon":"ability_racial_aberration","id":5310.0},{"icon":"achievement_boss_onyxia","id":4849.0},{"icon":"inv_misc_crop_01","id":5300.0},{"icon":"achievement_dungeon_bastion-of-twilight_valiona-theralion","id":4852.0},{"icon":"achievement_dungeon_bastion-of-twilight_twilightascendantcouncil","id":5311.0},{"icon":"spell_shadow_mindflay","id":5312.0},{"icon":"spell_deathknight_frostfever","id":5304.0},{"icon":"spell_shaman_staticshock","id":5305.0},{"icon":"ability_hunter_pet_worm","id":5094.0},{"icon":"achievement_dungeon_blackwingdescent_darkironcouncil","id":5107.0},{"icon":"achievement_dungeon_blackwingdescent_raid_maloriak","id":5108.0},{"icon":"achievement_dungeon_blackwingdescent_raid_atramedes","id":5109.0},{"icon":"achievement_dungeon_blackwingdescent_raid_chimaron","id":5115.0},{"icon":"achievement_dungeon_blackwingdescent_raid_nefarian","id":5116.0},{"icon":"achievement_dungeon_bastion-of-twilight_halfus-wyrmbreaker","id":5118.0},{"icon":"achievement_dungeon_bastion-of-twilight_valiona-theralion","id":5117.0},{"icon":"achievement_dungeon_bastion-of-twilight_twilightascendantcouncil","id":5119.0},{"icon":"achievement_dungeon_bastion-of-twilight_chogall-boss","id":5120.0},{"icon":"ability_druid_galewinds","id":5122.0},{"icon":"achievement_boss_murmur","id":5123.0}],"Meta":{"icon":"inv_helmet_100","id":4853.0},"TIERNAME":"T11 - Cataclysm Raids"},"T12":{"REQUIRED":[{"icon":"inv_misc_head_nerubian_01","id":5821.0},{"icon":"misc_arrowright","id":5810.0},{"icon":"spell_magic_polymorphrabbit","id":5813.0},{"icon":"achievement_zone_firelands","id":5829.0},{"icon":"spell_shadow_painandsuffering","id":5830.0},{"icon":"achievement_firelands-raid_fandral-staghelm","id":5799.0},{"icon":"achievement_boss_broodmotheraranae","id":5807.0},{"icon":"achievement_boss_lordanthricyst","id":5808.0},{"icon":"achievement_boss_shannox","id":5806.0},{"icon":"achievement_firelands-raid_alysra","id":5809.0},{"icon":"achievement_firelandsraid_balorocthegatekeeper","id":5805.0},{"icon":"achievement_firelands-raid_fandral-staghelm","id":5804.0}],"Meta":{"icon":"inv_mace_1h_sulfuron_d_01","id":5828.0},"TIERNAME":"T12 - Firelands"}} ';
				
		return true;
	}
}